# infra etcd certificates
- file:
    path: /etc/ssl/infra-etcd
    state: directory
    owner: etcd
    group: etcd
    mode: 0755

- copy:
    src: secret/ssl/infra/etcd-ca.pem
    dest: /etc/ssl/infra-etcd/ca.pem

- copy:
    src: secret/ssl/infra/{{ inventory_hostname }}/etcd-client.pem
    dest: /etc/ssl/infra-etcd/etcd-client.pem

- copy:
    src: secret/ssl/infra/{{ inventory_hostname }}/etcd-client-key.pem
    dest: /etc/ssl/infra-etcd/etcd-client-key.pem
    owner: etcd
    group: etcd
    mode: 0600

# kubernetes certificates
- file:
    path: /etc/kubernetes/ssl
    state: directory
    mode: 0755

- copy:
    src: secret/ssl/kubernetes/apiserver-ca.pem
    dest: /etc/kubernetes/ssl/apiserver-ca.pem

- copy:
    src: secret/ssl/kubernetes/{{ inventory_hostname }}/apiserver-client.pem
    dest: /etc/kubernetes/ssl/apiserver-client.pem

- copy:
    src: secret/ssl/kubernetes/{{ inventory_hostname }}/apiserver-client-key.pem
    dest: /etc/kubernetes/ssl/apiserver-client-key.pem
